config/routes.rb
Picgame::Application.routes.draw do
  devise_for :users, :controllers => {registrations: "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  resources :questions

  root :to => 'game#index'
  match '/game', to: 'game#index', via: 'get'
  post '/game' => 'game#evaluate'
  get '/leaderboard' => 'leaderboard#index'
  get '/invite' => 'invite#index'
  post '/invite' => 'invite#done'
  match '/newgame', to: 'game#index', via: 'get'
  post '/newgame' => 'game#index'

end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_attached_file :photo
	validates_attachment_presence :photo
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpg','image/jpeg', 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                          )
      end    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
 
   def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
   end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
	attr_accessor :random, :number, :attempt, :score
	def initialize
		@random = Question.all.shuffle
	end

	def index
		#Validate logged in
		@ques = @random
		access_level
		render :layout => 'application'
	end
	def evaluate
		@score = current_user.score
		@attempt = current_user.attempt
		if params[:answer] == params[:correct]
			@string = "Right answer."
			add_score
			@add = score
			@string = @string + @add.to_s
			increase_level
			#Generate next question/ Question of higher difficulty
		else
			@string = "Wrong answer."
			decrease_score
			increase_attempts
			if @attempt >= 3
				player = Leaderboard.new
				player.name = current_user.name
				player.score = current_user.score
				player.save!
				gameover
			end
			@add = score 
			@string = @string + @add.to_s
		end

		if @attempt <= 2
			redirect_to '/game' 
		end
	end

	def new
		newGame
		redirect_to '/newgame'
	end

	def gameover
		newGame
		render :layout => 'gameover'
	end

	private
	def score
		@score = current_user.score
		return @score
	end

	def add_score
		current_user.score = current_user.score + 3
		current_user.save!
	end

	def decrease_score
		current_user.score = current_user.score - 1
		current_user.save!
	end

	def access_level
		@number = current_user.level
		return @number
	end
	def increase_level
		current_user.level = current_user.level + 1 
		current_user.save!
	end

	def increase_attempts
		@attempt = current_user.attempt 
		@attempt = @attempt + 1
		current_user.attempt = @attempt
		current_user.save!
	end

	def newGame
		current_user.level = 0
		current_user.score  = 0
		current_user.attempt = 0
		current_user.save!
	end

end

app/controllers/invite_controller.rb
class InviteController < ApplicationController
	def index
	end

	def done
		FriendInvite.invite(current_user, params[:id]).deliver
		redirect_to '/'
	end

end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
	def index
		@all = Leaderboard.order("score desc").limit(10)
		@my = Leaderboard.where(name: current_user.name).order("id desc").limit(5)
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
def facebook     
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)      
     if @user.persisted?       
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    if not admin
      redirect_to "/game"
    end
    @questions = Question.all
  end

  def game
    if not admin
      redirect_to "/game"
    end
    @ques = Question(:all).sample(1)
  end
  
  # GET /questions/1
  # GET /questions/1.json
  def show
    if not admin
      redirect_to "/game"
    end
  end

  # GET /questions/new
  def new
    if not admin
      redirect_to "/game"
    end
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    if not admin
      redirect_to "/game"
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    if not admin
      redirect_to "/game"
    end
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    if not admin
      redirect_to "/game"
    end
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    if not admin
      redirect_to "/game"
    end
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:name, :marks, :answer, :difficulty, :level, :photo)
    end

    def admin
      if current_user.admin?
        return false
      else
        return true
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/invite_helper.rb
module InviteHelper
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/friend_invite/friend_invite.text.erb
Lets play on PicGame!
Click here to continue: 127.0.0.1:3000

Regards.

app/views/friend_invite/invite.text.erb
Lets play on PicGame!
Click here to continue: 127.0.0.1:3000

Regards.

app/views/game/_layout.html.erb
<h1><%= @add %></h1>

app/views/game/evaluate.html.erb
<h1><%= @string %></h1>
<h3><a href = "/game">Click here for the next question.</a></h3>

app/views/game/gameover.html.erb
<h1>Game Over!</h1>

app/views/game/index.html.erb
<div class="center hero-unit">
<h3>Level <%= current_user.level %></h3>
<%= image_tag @ques[current_user.level].photo.url %>
<br>
<%= form_tag("game", method: "post") do %>
  <%= label_tag(:answer, "Answer: ") %>
  <%= text_field_tag(:answer) %>
  <%= hidden_field_tag(:correct, value = @ques[current_user.level]["answer"]) %>
  <%= submit_tag("Go!") %>
<% end %>
</div>
<%= render 'layout' %>
</html>

app/views/invite/index.html.erb
<html>
<div class = "center hero-unit">
<%= form_tag("invite", method: "post") do %>
  <%= label_tag("Email Address") %>
  <%= text_field_tag(:id) %><br />
  <%= submit_tag("Invite!") %>
<% end %>
</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picgame</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Picgame", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/' %></li>
	            <li><%= link_to "Leaderboard", '/leaderboard'%></li>
              <li><%= link_to "View Previous Scores", '/leaderboard'%></li>
              <% if user_signed_in? %>
              <li><%= link_to "#{current_user.name} - Profile", edit_user_registration_path%></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <li><%= link_to "Invite", "/invite" %> </li>
              <% if not current_user.admin? %>
              <li><%= link_to "Questions", "/questions" %> </li>
              <% end %>
              <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>

              <% end %>
            </ul>
          </nav>
        </div>
      </div>
  </header>
<div class="container">
  <%= yield %>
</div>
</body>
<% if user_signed_in? %>
<div class = "center">Your score : <%= current_user.score %></div>
<div class = "center">Attempts : <%= current_user.attempt %></div>
<% end %>
<footer class="footer">
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</footer>
</html>

app/views/layouts/gameover.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Picgame</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Picgame", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '/' %></li>
	      <li><%= link_to "Leaderboard", '/leaderboard'%></li>
              <% if user_signed_in? %>
              <li><%= link_to current_user.name, edit_user_registration_path%></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <li><%= link_to "Invite", "/invite" %> </li>
              <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>

              <% end %>
            </ul>
          </nav>
        </div>
      </div>
  </header>
<div class="center">
	<h1>Game Over</h1>
  <%= button_to('New Game', 'newgame', :class => 'btn btn-default')  %>
</div>
</body>
<footer class="footer">
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</footer>
</html>

app/views/leaderboard/index.html.erb
<%= stylesheet_link_tag "leaderboard" %>
<h1>Leaderboard</h1>
<table class="table table-striped" >
	<thead>
		<tr>
			<th>Name</th>
			<th>Score </th>
        </tr>
		</thead>
		<tbody>
		    <% @all.each do |i|%>
			<tr>
				<td><%= i.name%></td>
				<td><%= i.score%></td>
			</tr>			
		    <% end %>
		</tbody>
</table>
<br>
<div class = "center">
<h4>Your Previous Scores</h4>
<table class="table table-striped" >
	<thead>
		<tr>
			<th>Name</th>
			<th>Score </th>
        </tr>
		</thead>
		<tbody>
		    <% @my.each do |i|%>
			<tr>
				<td><%= i.name%></td>
				<td><%= i.score%></td>
			</tr>			
		    <% end %>
		</tbody>
</table>
</div>
            

app/views/questions/_form.html.erb
<%= form_for @question, :html => {:multipart => true} do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div><%= f.file_field :photo %></div>
  <div class="actions">
    <%= f.submit "Submit"%>
  </div>

<% end %>

app/views/questions/edit.html.erb
<% if current_user.admin? %>

<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

<% else %>
<h1>Admin authorization required!</h1>
<% end %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Answer</th>
      <th>Level</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <td><%= question.answer %></td>
        <td><%= question.level %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<%= image_tag @question.photo.url%>
<p>
  <strong>Name:</strong>
  <%= @question.name %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Level:</strong>
  <%= @question.level %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>